### ISSUE TITLE
Relative Image url change when using proxy in Flutter Web

### ISSUE THREAD

**Issue by DattatreyaReddy** [sur950/any_link_preview#86]
As we know When using proxy url becomes 
```
https://corsproxy.org/https://www.google.com
or
https://api.codetabs.com/v1/proxy?quest=https://www.google.com
```
which returns image URL 
```
/logos/doodles/2024/seasonal-holidays-2024-6753651837110333-law.gif
```

But when we try to resolve the URL using the code below

https://github.com/sur950/any_link_preview/blob/bff7a3473be379bec653749526aa10add66d8720/lib/src/helpers/link_analyzer.dart#L217

it will return 
```
https://corsproxy.org/logos/doodles/2024/seasonal-holidays-2024-6753651837110333-law.gif
or 
https://api.codetabs.com/logos/doodles/2024/seasonal-holidays-2024-6753651837110333-law.gif
```
which is breaks the image

**Comment by sur950** [comment]
Hi, Thanks for bringing this to my notice. I will fix it by removing the proxy URL and adding the domain of the BASE URL.

Thanks!

**Comment by sur950** [comment]
Hi,

I have applied a fixed in Version-3.0.3, Have a look and do confirm if it's fixed or still open.

**Comment by DattatreyaReddy** [comment]
Hi @sur950, Sorry for the late replay,

it seems you removed the proxy URL support completely.

https://github.com/sur950/any_link_preview/blob/a33a8aee7efacdb1710cbd0e49e048f9ff7ce378/lib/src/helpers/link_preview.dart#L191

but this is not the issue, the issue is with generating image URLs, which is not fixed even now as the code below removes the query params of the URL I send, that is if I manually append the proxy URL to my URL.
if I don't append the proxy URL I'll get a CROS error (I'm running my app on the web)

https://github.com/sur950/any_link_preview/blob/a33a8aee7efacdb1710cbd0e49e048f9ff7ce378/lib/src/helpers/link_analyzer.dart#L215
